In [8]:
from GNNProject.utils import *
from GNNProject.dataset import *
from GNNProject.model import *
from GNNProject.classifier import *

In [9]:
if torch.cuda.is_available():  
  dev = "cuda:0" 
else:  
  dev = "cpu"  
device = torch.device(dev)  

## Generate a synthetic dataset

In [10]:
n_classes=3
n_features=100
n_char_features=10
n_obs_train=500
n_obs_test=1000
epochs=20

In [11]:
dataset = Dataset(tag='EXP1')

dataset.create_syn(n_classes = n_classes, 
                   n_obs_train = n_obs_train, 
                   n_obs_test= n_obs_test, 
                   n_features=n_features,
                   n_char_features = n_char_features,  
                   model ='BA',
                   syn_method="sign")

dataset.create_graph(alphas=1)


train_dataloader = dataset._dataloader('train',use_true_graph=True,batch_size=16)
test_dataloader  = dataset._dataloader('test',use_true_graph=True,batch_size=16)

## Fit and evaluate a GNN

In [12]:
clf = Classifier(n_features=n_features,
        n_classes=n_classes,
        n_hidden_GNN=[8],
        n_hidden_FC=[],
        dropout_FC=0.2,
        dropout_GNN=0.2,
        K=2,
        classifier='GraphSAGE', 
        lr=.001,
        momentum=.9,
        log_dir="runs/GNN_TrueGraph",
        device = device) 

clf.fit(train_dataloader, epochs = epochs, test_dataloader=test_dataloader,verbose=True)
_ = clf.eval(test_dataloader, verbose=True)

[1] loss: 0.068
[3] loss: 0.005
[5] loss: 0.000
[7] loss: 0.000
[9] loss: 0.001
[11] loss: 0.000
[13] loss: 0.000
[15] loss: 0.000
[17] loss: 0.000
[19] loss: 0.000
Accuracy: 1.000
Confusion Matrix:n [[1000    0    0]
 [   0 1000    0]
 [   0    0 1000]]
Precision: 1.000
Recall: 1.000
f1_score: 1.000


## Fit and evaluate a MLP

In [13]:
clf = Classifier(n_features=n_features,
        n_classes=n_classes,
        n_hidden_GNN=[],
        n_hidden_FC=[40],
        dropout_FC=0.2,
        classifier='MLP', 
        lr=.001, 
        momentum=.9,
        log_dir="runs/MLP")
clf.fit(train_dataloader, epochs = epochs, test_dataloader=test_dataloader,verbose=True)
_ = clf.eval(test_dataloader, verbose=True)

[1] loss: 2.046
[3] loss: 0.159
[5] loss: 0.126
[7] loss: 0.134
[9] loss: 0.101
[11] loss: 0.111
[13] loss: 0.047
[15] loss: 0.085
[17] loss: 0.054
[19] loss: 0.057
Accuracy: 1.000
Confusion Matrix:n [[1000    0    0]
 [   0 1000    0]
 [   0    0 1000]]
Precision: 1.000
Recall: 1.000
f1_score: 1.000
